### ISSUE TITLE
PyPI please

### ISSUE THREAD

**Issue by globophobe** [QbDesu/django-tui.editor#1]
Hey, this is pretty cool! I was just about to start writing the same thing. Fortunately, you wrote it first :smile: 

How about a pypi release?

**Comment by QbDesu** [comment]
https://pypi.org/project/django-tuieditor/
It's my first time packaging a module so I hope everything is configured correctly. I was quite surprised to get an issue on this little project which is a byproduct of https://github.com/lukas2511/voctoconf . Also I don't have much experience with django development so I hope at least this module turned out alright. (Demo of the StaticMarkdownViewerWidget: https://voctoconf.kurz.pw/event)

**Comment by globophobe** [comment]
Hi, thanks! The pypi release seems to be missing `static` and `templates`. 

Writing `setup.py` is fun I guess, an alternative is https://github.com/python-poetry/poetry

**Comment by QbDesu** [comment]
oh thanks for reporting it. I should have tested it better. I'll fix it in the evening and test it this time.

**Comment by globophobe** [comment]
Also, maybe add to https://djangopackages.org/ 

Takes like 10 secs

**Comment by QbDesu** [comment]
The new version 0.2.0 includes now includes the non-python file assets. This time I tested it in the voctoconf project and it seems to be set up correctly.
I also added it to django packages, thanks for pointing it out: https://djangopackages.org/packages/p/django-tuieditor/
